2015-03-05T14:36:16.073Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:16 GMT+0100 (CET), pid=2094, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38338560, heapTotal=33335808, heapUsed=17252144, loadavg=[0.0830078125, 0.03125, 0.05078125], uptime=185908, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:16.126Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:16 GMT+0100 (CET), pid=2094, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39141376, heapTotal=34339328, heapUsed=17792156, loadavg=[0.0830078125, 0.03125, 0.05078125], uptime=185908, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:16.184Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:16 GMT+0100 (CET), pid=2094, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39411712, heapTotal=34339328, heapUsed=18270880, loadavg=[0.0830078125, 0.03125, 0.05078125], uptime=185908, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:19.422Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:19 GMT+0100 (CET), pid=2103, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38428672, heapTotal=33335808, heapUsed=17256568, loadavg=[0.15625, 0.04736328125, 0.0556640625], uptime=185912, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:19.473Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:19 GMT+0100 (CET), pid=2103, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39231488, heapTotal=34339328, heapUsed=17796488, loadavg=[0.15625, 0.04736328125, 0.0556640625], uptime=185912, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:19.525Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:19 GMT+0100 (CET), pid=2103, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39501824, heapTotal=34339328, heapUsed=18274936, loadavg=[0.15625, 0.04736328125, 0.0556640625], uptime=185912, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:22.744Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:22 GMT+0100 (CET), pid=2112, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38535168, heapTotal=33335808, heapUsed=17120364, loadavg=[0.15625, 0.04736328125, 0.0556640625], uptime=185915, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:22.795Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:22 GMT+0100 (CET), pid=2112, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39337984, heapTotal=34339328, heapUsed=17791904, loadavg=[0.15625, 0.04736328125, 0.0556640625], uptime=185915, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:22.848Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:22 GMT+0100 (CET), pid=2112, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39878656, heapTotal=34339328, heapUsed=18270564, loadavg=[0.15625, 0.04736328125, 0.0556640625], uptime=185915, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:26.069Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:26 GMT+0100 (CET), pid=2121, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38309888, heapTotal=33335808, heapUsed=17254708, loadavg=[0.2236328125, 0.06298828125, 0.060546875], uptime=185918, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:26.120Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:26 GMT+0100 (CET), pid=2121, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39112704, heapTotal=34339328, heapUsed=17794724, loadavg=[0.2236328125, 0.06298828125, 0.060546875], uptime=185918, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:26.173Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:26 GMT+0100 (CET), pid=2121, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39383040, heapTotal=34339328, heapUsed=18273276, loadavg=[0.2236328125, 0.06298828125, 0.060546875], uptime=185918, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:29.326Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:29 GMT+0100 (CET), pid=2130, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=41058304, heapTotal=31304448, heapUsed=20600704, loadavg=[0.28564453125, 0.07861328125, 0.0654296875], uptime=185921, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:29.382Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:29 GMT+0100 (CET), pid=2130, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=41598976, heapTotal=32307968, heapUsed=21139868, loadavg=[0.28564453125, 0.07861328125, 0.0654296875], uptime=185922, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:29.458Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:29 GMT+0100 (CET), pid=2130, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=43823104, heapTotal=34339328, heapUsed=16561920, loadavg=[0.28564453125, 0.07861328125, 0.0654296875], uptime=185922, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:32.728Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:32 GMT+0100 (CET), pid=2140, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38330368, heapTotal=33335808, heapUsed=17253756, loadavg=[0.28564453125, 0.07861328125, 0.0654296875], uptime=185925, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:32.782Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:32 GMT+0100 (CET), pid=2140, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39133184, heapTotal=34339328, heapUsed=17793708, loadavg=[0.28564453125, 0.07861328125, 0.0654296875], uptime=185925, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:32.837Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:32 GMT+0100 (CET), pid=2140, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39403520, heapTotal=34339328, heapUsed=18272352, loadavg=[0.28564453125, 0.07861328125, 0.0654296875], uptime=185925, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:36.054Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:36 GMT+0100 (CET), pid=2150, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38420480, heapTotal=32320128, heapUsed=17126908, loadavg=[0.3427734375, 0.09375, 0.0703125], uptime=185928, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:36.106Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:36 GMT+0100 (CET), pid=2150, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39223296, heapTotal=34339328, heapUsed=17798276, loadavg=[0.3427734375, 0.09375, 0.0703125], uptime=185928, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:36.159Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:36 GMT+0100 (CET), pid=2150, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39763968, heapTotal=34339328, heapUsed=18276752, loadavg=[0.3427734375, 0.09375, 0.0703125], uptime=185928, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:39.359Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:39 GMT+0100 (CET), pid=2159, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38834176, heapTotal=32320128, heapUsed=17132992, loadavg=[0.3955078125, 0.10888671875, 0.0751953125], uptime=185932, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:39.410Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:39 GMT+0100 (CET), pid=2159, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39645184, heapTotal=33323648, heapUsed=17803864, loadavg=[0.3955078125, 0.10888671875, 0.0751953125], uptime=185932, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:39.464Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:39 GMT+0100 (CET), pid=2159, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=40185856, heapTotal=33323648, heapUsed=18282280, loadavg=[0.3955078125, 0.10888671875, 0.0751953125], uptime=185932, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:43.273Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:43 GMT+0100 (CET), pid=2168, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38293504, heapTotal=33335808, heapUsed=17246828, loadavg=[0.3955078125, 0.10888671875, 0.0751953125], uptime=185935, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:43.330Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:43 GMT+0100 (CET), pid=2168, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39096320, heapTotal=34339328, heapUsed=17786968, loadavg=[0.3955078125, 0.10888671875, 0.0751953125], uptime=185935, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:43.383Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:43 GMT+0100 (CET), pid=2168, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39366656, heapTotal=34339328, heapUsed=18265412, loadavg=[0.3955078125, 0.10888671875, 0.0751953125], uptime=185936, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:46.606Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:46 GMT+0100 (CET), pid=2186, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38526976, heapTotal=33335808, heapUsed=17256928, loadavg=[0.44384765625, 0.12353515625, 0.080078125], uptime=185939, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:46.657Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:46 GMT+0100 (CET), pid=2186, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39329792, heapTotal=34339328, heapUsed=17797076, loadavg=[0.44384765625, 0.12353515625, 0.080078125], uptime=185939, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:46.710Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:46 GMT+0100 (CET), pid=2186, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39600128, heapTotal=34339328, heapUsed=18275720, loadavg=[0.44384765625, 0.12353515625, 0.080078125], uptime=185939, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:50.576Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:50 GMT+0100 (CET), pid=2195, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38395904, heapTotal=32320128, heapUsed=17127076, loadavg=[0.568359375, 0.15478515625, 0.09033203125], uptime=185943, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:50.627Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:50 GMT+0100 (CET), pid=2195, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39198720, heapTotal=34339328, heapUsed=17798604, loadavg=[0.568359375, 0.15478515625, 0.09033203125], uptime=185943, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:50.680Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:50 GMT+0100 (CET), pid=2195, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39739392, heapTotal=34339328, heapUsed=18277200, loadavg=[0.568359375, 0.15478515625, 0.09033203125], uptime=185943, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:53.879Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:53 GMT+0100 (CET), pid=2210, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38412288, heapTotal=32320128, heapUsed=17125604, loadavg=[0.60302734375, 0.1689453125, 0.09521484375], uptime=185946, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:53.930Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:53 GMT+0100 (CET), pid=2210, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39215104, heapTotal=34339328, heapUsed=17797156, loadavg=[0.60302734375, 0.1689453125, 0.09521484375], uptime=185946, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:53.983Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:53 GMT+0100 (CET), pid=2210, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39755776, heapTotal=34339328, heapUsed=18275800, loadavg=[0.60302734375, 0.1689453125, 0.09521484375], uptime=185946, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:57.188Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:36:57 GMT+0100 (CET), pid=2219, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38400000, heapTotal=32320128, heapUsed=17126628, loadavg=[0.60302734375, 0.1689453125, 0.09521484375], uptime=185949, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:36:57.240Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:57 GMT+0100 (CET), pid=2219, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39202816, heapTotal=34339328, heapUsed=17798180, loadavg=[0.60302734375, 0.1689453125, 0.09521484375], uptime=185949, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:36:57.292Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:36:57 GMT+0100 (CET), pid=2219, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39743488, heapTotal=34339328, heapUsed=18276804, loadavg=[0.60302734375, 0.1689453125, 0.09521484375], uptime=185949, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:00.489Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:37:00 GMT+0100 (CET), pid=2228, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39137280, heapTotal=33335808, heapUsed=17229364, loadavg=[0.634765625, 0.1826171875, 0.10009765625], uptime=185953, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:37:00.541Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:00 GMT+0100 (CET), pid=2228, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39677952, heapTotal=34339328, heapUsed=17769432, loadavg=[0.634765625, 0.1826171875, 0.10009765625], uptime=185953, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:00.593Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:00 GMT+0100 (CET), pid=2228, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=40218624, heapTotal=34339328, heapUsed=18248440, loadavg=[0.634765625, 0.1826171875, 0.10009765625], uptime=185953, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:03.808Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:37:03 GMT+0100 (CET), pid=2237, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38522880, heapTotal=31304448, heapUsed=17244040, loadavg=[0.6640625, 0.1962890625, 0.10498046875], uptime=185956, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:37:03.861Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:03 GMT+0100 (CET), pid=2237, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39333888, heapTotal=33323648, heapUsed=17915364, loadavg=[0.6640625, 0.1962890625, 0.10498046875], uptime=185956, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:03.914Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:03 GMT+0100 (CET), pid=2237, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39968768, heapTotal=34339328, heapUsed=18393972, loadavg=[0.6640625, 0.1962890625, 0.10498046875], uptime=185956, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:07.100Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:37:07 GMT+0100 (CET), pid=2246, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38338560, heapTotal=33335808, heapUsed=17124268, loadavg=[0.6640625, 0.1962890625, 0.10498046875], uptime=185959, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:37:07.151Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:07 GMT+0100 (CET), pid=2246, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39141376, heapTotal=34339328, heapUsed=17796004, loadavg=[0.6640625, 0.1962890625, 0.10498046875], uptime=185959, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:07.204Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:07 GMT+0100 (CET), pid=2246, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39682048, heapTotal=34339328, heapUsed=18274736, loadavg=[0.6640625, 0.1962890625, 0.10498046875], uptime=185959, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:10.341Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:37:10 GMT+0100 (CET), pid=2255, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=41046016, heapTotal=31304448, heapUsed=20464264, loadavg=[0.69091796875, 0.20947265625, 0.10986328125], uptime=185962, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:37:10.398Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:10 GMT+0100 (CET), pid=2255, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=41586688, heapTotal=32307968, heapUsed=21137872, loadavg=[0.69091796875, 0.20947265625, 0.10986328125], uptime=185963, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:10.473Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:10 GMT+0100 (CET), pid=2255, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=43954176, heapTotal=34339328, heapUsed=16562008, loadavg=[0.69091796875, 0.20947265625, 0.10986328125], uptime=185963, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:13.643Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:37:13 GMT+0100 (CET), pid=2264, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38473728, heapTotal=32320128, heapUsed=17085940, loadavg=[0.69091796875, 0.20947265625, 0.10986328125], uptime=185966, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:37:13.694Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:13 GMT+0100 (CET), pid=2264, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39276544, heapTotal=34339328, heapUsed=17757360, loadavg=[0.7158203125, 0.22265625, 0.11474609375], uptime=185966, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:13.747Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:13 GMT+0100 (CET), pid=2264, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39817216, heapTotal=34339328, heapUsed=18236116, loadavg=[0.7158203125, 0.22265625, 0.11474609375], uptime=185966, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:16.958Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:37:16 GMT+0100 (CET), pid=2273, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38412288, heapTotal=32320128, heapUsed=17124716, loadavg=[0.7158203125, 0.22265625, 0.11474609375], uptime=185969, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:37:17.015Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:16 GMT+0100 (CET), pid=2273, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39215104, heapTotal=34339328, heapUsed=17796256, loadavg=[0.7158203125, 0.22265625, 0.11474609375], uptime=185969, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:17.071Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:17 GMT+0100 (CET), pid=2273, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39755776, heapTotal=34339328, heapUsed=18275012, loadavg=[0.7158203125, 0.22265625, 0.11474609375], uptime=185969, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:20.713Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:37:20 GMT+0100 (CET), pid=2282, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=38236160, heapTotal=32320128, heapUsed=17133804, loadavg=[0.73876953125, 0.2353515625, 0.11962890625], uptime=185973, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:37:20.791Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:20 GMT+0100 (CET), pid=2282, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39038976, heapTotal=34339328, heapUsed=17805176, loadavg=[0.73876953125, 0.2353515625, 0.11962890625], uptime=185973, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:20.871Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:20 GMT+0100 (CET), pid=2282, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[/usr/bin/node, /mnt/sdcard/server/app], rss=39579648, heapTotal=34339328, heapUsed=18283608, loadavg=[0.73876953125, 0.2353515625, 0.11962890625], uptime=185973, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:26.656Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 05 2015 15:37:26 GMT+0100 (CET), pid=2301, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[node, /mnt/sdcard/server/app], rss=38547456, heapTotal=33335808, heapUsed=17268848, loadavg=[0.759765625, 0.248046875, 0.12451171875], uptime=185979, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-05T14:37:26.708Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:26 GMT+0100 (CET), pid=2301, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[node, /mnt/sdcard/server/app], rss=39079936, heapTotal=34339328, heapUsed=17809048, loadavg=[0.759765625, 0.248046875, 0.12451171875], uptime=185979, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-05T14:37:26.761Z - error: uncaughtException: failed to connect to [localhost:27017] date=Thu Mar 05 2015 15:37:26 GMT+0100 (CET), pid=2301, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[node, /mnt/sdcard/server/app], rss=39620608, heapTotal=34339328, heapUsed=18288852, loadavg=[0.759765625, 0.248046875, 0.12451171875], uptime=185979, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2015-03-11T23:21:29.365Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 12 2015 00:21:29 GMT+0100 (CET), pid=5741, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[node, /mnt/sdcard/server/app], rss=38420480, heapTotal=32320128, heapUsed=17124680, loadavg=[0.0830078125, 0.03125, 0.05078125], uptime=735822, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2015-03-11T23:22:30.871Z - error: uncaughtException: Route.get() requires callback functions but got a [object Undefined] date=Thu Mar 12 2015 00:22:30 GMT+0100 (CET), pid=5762, uid=1000, gid=1000, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[node, /mnt/sdcard/server/app], rss=38629376, heapTotal=33335808, heapUsed=17219440, loadavg=[0.0302734375, 0.025390625, 0.04541015625], uptime=735883, trace=[column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=, line=160, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=15, file=/mnt/sdcard/server/node_modules/express/lib/router/route.js, function=Route.(anonymous function) [as get], line=156, method=(anonymous function) [as get], native=false, column=10, file=/mnt/sdcard/server/app/routes/memory.js, function=module.exports, line=9, method=exports, native=false, column=19, file=/mnt/sdcard/server/app.js, function=null, line=29, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=/mnt/sdcard/server/app.js, function=, line=28, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false], stack=[Error: Route.get() requires callback functions but got a [object Undefined],     at Route.<anonymous> (/mnt/sdcard/server/node_modules/express/lib/router/route.js:160:15),     at Array.forEach (native),     at Route.(anonymous function) [as get] (/mnt/sdcard/server/node_modules/express/lib/router/route.js:156:15),     at module.exports (/mnt/sdcard/server/app/routes/memory.js:9:10),     at /mnt/sdcard/server/app.js:29:19,     at Array.forEach (native),     at Object.<anonymous> (/mnt/sdcard/server/app.js:28:8),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]
2011-01-01T12:02:43.655Z - error: uncaughtException: failed to connect to [localhost:27017] date=Sat Jan 01 2011 13:02:43 GMT+0100 (CET), pid=801, uid=0, gid=0, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[node, /mnt/sdcard/server/app], rss=38928384, heapTotal=33323648, heapUsed=17379044, loadavg=[0.22119140625, 0.2197265625, 0.09716796875], uptime=166, trace=[column=74, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=549, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=533, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
2011-01-01T12:02:43.728Z - error: uncaughtException: failed to connect to [localhost:27017] date=Sat Jan 01 2011 13:02:43 GMT+0100 (CET), pid=801, uid=0, gid=0, cwd=/mnt/sdcard/server, execPath=/usr/bin/node, version=v0.11.15, argv=[node, /mnt/sdcard/server/app], rss=39751680, heapTotal=34339328, heapUsed=18192868, loadavg=[0.22119140625, 0.2197265625, 0.09716796875], uptime=166, trace=[column=74, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js, function=, line=555, method=null, native=false, column=17, file=events.js, function=emit, line=118, method=null, native=false, column=15, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js, function=, line=150, method=null, native=false, column=17, file=events.js, function=emit, line=110, method=null, native=false, column=10, file=/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js, function=, line=534, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=14, file=net.js, function=null, line=451, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: failed to connect to [localhost:27017],     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74),     at emit (events.js:118:17),     at null.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15),     at emit (events.js:110:17),     at Socket.<anonymous> (/mnt/sdcard/server/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10),     at Socket.emit (events.js:107:17),     at net.js:451:14,     at process._tickCallback (node.js:355:11)]
